### ISSUE TITLE
How to resume the animation

### ISSUE THREAD

**Issue by Claudio725** [gauravk95/audio-visualizer-android#2]
Hi guys! I have apreciatted your plugin, but I need to know how to resume the process after stop the same.

**Comment by gauravk95** [comment]
When resuming the process, you can set the Audio Session ID again, i.e reset the visualizer like this

`int audioSessionId = mAudioPlayer.getAudioSessionId();`
`if (audioSessionId != -1)
            mVisualizer.setAudioSessionId(audioSessionId);`

I will add new calls/methods, to make it easier to handle such situations, soon, but for now you may use the following solution.
Hope this helps!

**Comment by gauravk95** [comment]
I have updated the sample app to show starting and stopping the audio. Hope that helps!
